//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Therapy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public System.TimeSpan Start_date { get; set; }
        public System.TimeSpan End_date { get; set; }
        public string IsActivated { get; set; }
        public string CustomerId { get; set; }
        public string AdministorId { get; set; }
        public string TherapistId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Administor Administor { get; set; }
        public virtual Therapist Therapist { get; set; }
    }
}
